name: Telegram Test

on:
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: Kirim pesan ke Telegram
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
          -d chat_id="@InfolokerCiayumajakuning" \
          -d text="✅ GitHub Actions berhasil terhubung!"
